사람인 데이터 분석 채용공고 수집을 위한 코드

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait

from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

from selenium.common.exceptions import NoSuchElementException
import time
import re

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# 한글 폰트 설정
plt.rc('font', family = 'AppleGothic')

In [2]:
# Selenium으로 웹 드라이버 실행
service = Service(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

url ='https://www.saramin.co.kr/zf_user/'
driver.get(url)
driver.implicitly_wait(0.5) # 응답 바로 읽지 않고 기다려주기

# 검색어 버튼 클릭 1
search_click = driver.find_elements(By.CLASS_NAME, 'btn_search')
search_click[0].click()
time.sleep(2)

# 검색어 입력
search_input = driver.find_element(By.ID, 'ipt_keyword_recruit')
search_input.send_keys('데이터 분석') 
time.sleep(2)

# 검색어 버튼 클릭 2
search_click[1].click()
time.sleep(2)

recruit = []
url = []
company = []
detail = []

# 전체정보
search_info = driver.find_elements(By.CSS_SELECTOR, "[class*='item_recruit']")

for i in range(len(search_info)):
    title_link = search_info[i].find_element(By.CLASS_NAME, 'job_tit') # 제목과 링크
    Col_recruit = title_link.text # 제목
    Col_url = title_link.find_element(By.TAG_NAME, 'a').get_attribute('href') # 링크
    Col_company = search_info[i].find_element(By.CLASS_NAME, 'corp_name').text # 회사명
    Col_detail = search_info[i].find_element(By.CLASS_NAME, 'job_condition').text.split('\n') # 세부조건

    recruit.append(Col_recruit)
    url.append(Col_url)
    company.append(Col_company)
    detail.append(Col_detail)

df_saramin = pd.DataFrame({'Site':'Saramin', 'Col_company':company, 'Col_recruit':recruit, 'Col_detail':detail, 'Col_url':url})
driver.quit()
display(df_saramin.head())
display(df_saramin.tail())

,Site,Col_company,Col_recruit,Col_detail,Col_url
0,Saramin,넛지헬스케어(주),[캐시워크] 데이터분석 담당 채용전환형 인턴,"[서울 강남구, 신입, 대졸↑, 인턴직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
1,Saramin,(주)넥슨코리아,[인텔리전스랩스그룹] 게임 데이터 분석가,"[경기 성남시 분당구, 경력, 학력무관, 정규직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
2,Saramin,(주)에스피파트너스,AI·빅데이터 분석 및 컨설팅 신입·경력 채용,"[경기 수원시 영통구, 신입·경력, 대졸↑, 정규직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
3,Saramin,(주)넥슨코리아,[플랫폼본부] 마비노기시너지실 데이터 분석가,"[경기 성남시 분당구, 경력무관, 학력무관, 정규직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
4,Saramin,(주)넥슨코리아,[플랫폼본부] 데이터 분석가,"[경기 성남시 분당구, 경력3년↑, 학력무관, 정규직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...

,Site,Col_company,Col_recruit,Col_detail,Col_url
35,Saramin,(주)바로팜,[비알피커넥트]데이터 분석가(계약직),"[서울 강남구, 경력 3~15년, 학력무관, 계약직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
36,Saramin,펑타이그레이터차이나(유),[PTKOREA] 데이터 분석가,"[서울 강남구, 경력 5~9년, 대졸↑, 정규직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
37,Saramin,(주)케이브레인컴퍼니,ISP·데이터기반행정 컨설턴트(데이터 분석/품질),"[서울 동작구, 경력3년↑, 대졸↑, 정규직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
38,Saramin,넛지헬스케어(주),[캐시워크] 데이터분석 담당 산업기능요원 (병역특례),"[서울 강남구, 경력무관, 학력무관, 산업기능요원·현역]",https://www.saramin.co.kr/zf_user/jobs/relay/v...
39,Saramin,넛지헬스케어(주),[캐시워크] 데이터엔지니어 채용전환형 인턴,"[서울 강남구, 신입, 학력무관, 인턴직]",https://www.saramin.co.kr/zf_user/jobs/relay/v...

In [3]:
# 사람인 데이터 저장
df_saramin.to_csv('data_tmp/data_saramin.csv', index=False, encoding='utf-8-sig')